name: Select incoming branch from pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  select-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
