name: Example workflow

on:
  pull_request:
    types: [opened]

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Print current branch
      run: echo "Current branch: ${{ github.ref }}"
      
    - name: Print incoming branch
      run: echo "Incoming branch: ${{ github.head_ref }}"
      if: github.event_name == 'pull_request'
